export const GlobalStyles = {
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  modalContainer: {
    flex: 1,
    //alignItems: 'center',
    //justifyContent: 'center',
  },
  modalBackground: {
    width: '80%',
    borderRadius: 30,
    padding: 30,
    marginTop: 100,
    marginBottom: 20,
    alignSelf: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.5,
    elevation: 16,
    backgroundColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  text: {
    marginVertical: 20,
    textAlign: 'center',
    fontSize: 18,
    color: 'black',
  },
  nameText: {
    color: '#555',
    fontSize: 18,
  },
  valueText: {
    color: 'black',
    fontSize: 18,
    marginBottom: 6,
  },
  input: {
    color: 'black',
    fontSize: 20,
    marginBottom: 10,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  card: {
    backgroundColor: 'pink',
    marginTop: 12,
    marginHorizontal: 20,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 10,
  },
};
